var dataInfo = [
    {
        "img1":"img/01.png",
        "img2":"img/01a.png",
        "info":"信息管家"
    },
    {
        "img1":"img/01.png",
        "img2":"img/01a.png",
        "info":"无线音乐专区"
    },
    {
        "img1":"img/01.png",
        "img2":"img/01a.png",
        "info":"手机证券"
    },
    {
        "img1":"img/01.png",
        "img2":"img/01a.png",
        "info":"飞信"
    },
    {
        "img1":"img/01.png",
        "img2":"img/01a.png",
        "info":"短信回执"
    }
];